version: '3.7'

services:
  app:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      PORT: ${PORT:-3000}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      DB_NAME: ${DB_NAME:-appointment_db}
      JWT_SECRET: ${JWT_SECRET:-jwt_secret}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-password}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
